CREATE TABLE IF NOT EXISTS users(                                                                  
	id serial PRIMARY KEY,
	username VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS confirmation_users(
	id serial PRIMARY KEY,
	activated BOOLEAN DEFAULT FALSE,
	user_id INT NOT NULL,
	CONSTRAINT fk_users
		FOREIGN KEY(user_id)
			REFERENCES users(id)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS password_resets(
  id serial PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  resend_expired INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS articles(
	id serial PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	content VARCHAR(255) NOT NULL,
	create_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	author_id INT NOT NULL,
	CONSTRAINT fk_users
		FOREIGN KEY(author_id)
			REFERENCES users(id)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);
